//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfApp6.ServiceReference1.STypes))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfApp6.ServiceReference1.Comments))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfApp6.ServiceReference1.Location))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfApp6.ServiceReference1.LType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfApp6.ServiceReference1.Person))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STypes", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class STypes : WpfApp6.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comments", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Comments : WpfApp6.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApp6.ServiceReference1.Person CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApp6.ServiceReference1.Location LocField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Cdate {
            get {
                return this.CdateField;
            }
            set {
                if ((this.CdateField.Equals(value) != true)) {
                    this.CdateField = value;
                    this.RaisePropertyChanged("Cdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApp6.ServiceReference1.Person Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApp6.ServiceReference1.Location Loc {
            get {
                return this.LocField;
            }
            set {
                if ((object.ReferenceEquals(this.LocField, value) != true)) {
                    this.LocField = value;
                    this.RaisePropertyChanged("Loc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Location : WpfApp6.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApp6.ServiceReference1.LType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des {
            get {
                return this.DesField;
            }
            set {
                if ((object.ReferenceEquals(this.DesField, value) != true)) {
                    this.DesField = value;
                    this.RaisePropertyChanged("Des");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApp6.ServiceReference1.LType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LType", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class LType : WpfApp6.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Person : WpfApp6.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApp6.ServiceReference1.STypes STypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SYearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrustedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApp6.ServiceReference1.STypes SType {
            get {
                return this.STypeField;
            }
            set {
                if ((object.ReferenceEquals(this.STypeField, value) != true)) {
                    this.STypeField = value;
                    this.RaisePropertyChanged("SType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SYears {
            get {
                return this.SYearsField;
            }
            set {
                if ((this.SYearsField.Equals(value) != true)) {
                    this.SYearsField = value;
                    this.RaisePropertyChanged("SYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Trusted {
            get {
                return this.TrustedField;
            }
            set {
                if ((this.TrustedField.Equals(value) != true)) {
                    this.TrustedField = value;
                    this.RaisePropertyChanged("Trusted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="STypeList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="STypes")]
    [System.SerializableAttribute()]
    public class STypeList : System.Collections.Generic.List<WpfApp6.ServiceReference1.STypes> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PersonList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Person")]
    [System.SerializableAttribute()]
    public class PersonList : System.Collections.Generic.List<WpfApp6.ServiceReference1.Person> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CommentsList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Comments")]
    [System.SerializableAttribute()]
    public class CommentsList : System.Collections.Generic.List<WpfApp6.ServiceReference1.Comments> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LocationList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Location")]
    [System.SerializableAttribute()]
    public class LocationList : System.Collections.Generic.List<WpfApp6.ServiceReference1.Location> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LTypeList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="LType")]
    [System.SerializableAttribute()]
    public class LTypeList : System.Collections.Generic.List<WpfApp6.ServiceReference1.LType> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogIn", ReplyAction="http://tempuri.org/IService1/LogInResponse")]
        WpfApp6.ServiceReference1.Person LogIn(string uname, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogIn", ReplyAction="http://tempuri.org/IService1/LogInResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.Person> LogInAsync(string uname, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPerson", ReplyAction="http://tempuri.org/IService1/InsertPersonResponse")]
        int InsertPerson(WpfApp6.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPerson", ReplyAction="http://tempuri.org/IService1/InsertPersonResponse")]
        System.Threading.Tasks.Task<int> InsertPersonAsync(WpfApp6.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllTypes", ReplyAction="http://tempuri.org/IService1/SelectAllTypesResponse")]
        WpfApp6.ServiceReference1.STypeList SelectAllTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllTypes", ReplyAction="http://tempuri.org/IService1/SelectAllTypesResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.STypeList> SelectAllTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllPersons", ReplyAction="http://tempuri.org/IService1/SelectAllPersonsResponse")]
        WpfApp6.ServiceReference1.PersonList SelectAllPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllPersons", ReplyAction="http://tempuri.org/IService1/SelectAllPersonsResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.PersonList> SelectAllPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePerson", ReplyAction="http://tempuri.org/IService1/UpdatePersonResponse")]
        void UpdatePerson(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePerson", ReplyAction="http://tempuri.org/IService1/UpdatePersonResponse")]
        System.Threading.Tasks.Task UpdatePersonAsync(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        void Delete(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllC", ReplyAction="http://tempuri.org/IService1/SelectAllCResponse")]
        WpfApp6.ServiceReference1.CommentsList SelectAllC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllC", ReplyAction="http://tempuri.org/IService1/SelectAllCResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.CommentsList> SelectAllCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllL", ReplyAction="http://tempuri.org/IService1/SelectAllLResponse")]
        WpfApp6.ServiceReference1.LocationList SelectAllL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllL", ReplyAction="http://tempuri.org/IService1/SelectAllLResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.LocationList> SelectAllLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/comment_creator", ReplyAction="http://tempuri.org/IService1/comment_creatorResponse")]
        void comment_creator(WpfApp6.ServiceReference1.Person p, WpfApp6.ServiceReference1.Location loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/comment_creator", ReplyAction="http://tempuri.org/IService1/comment_creatorResponse")]
        System.Threading.Tasks.Task comment_creatorAsync(WpfApp6.ServiceReference1.Person p, WpfApp6.ServiceReference1.Location loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCbyP", ReplyAction="http://tempuri.org/IService1/SelectCbyPResponse")]
        WpfApp6.ServiceReference1.CommentsList SelectCbyP(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCbyP", ReplyAction="http://tempuri.org/IService1/SelectCbyPResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.CommentsList> SelectCbyPAsync(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lby_Person", ReplyAction="http://tempuri.org/IService1/Lby_PersonResponse")]
        WpfApp6.ServiceReference1.LocationList Lby_Person(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Lby_Person", ReplyAction="http://tempuri.org/IService1/Lby_PersonResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.LocationList> Lby_PersonAsync(WpfApp6.ServiceReference1.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/all_l_types", ReplyAction="http://tempuri.org/IService1/all_l_typesResponse")]
        WpfApp6.ServiceReference1.LTypeList all_l_types();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/all_l_types", ReplyAction="http://tempuri.org/IService1/all_l_typesResponse")]
        System.Threading.Tasks.Task<WpfApp6.ServiceReference1.LTypeList> all_l_typesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        byte[] GetImage(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        void SaveImage(byte[] imgArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        System.Threading.Tasks.Task SaveImageAsync(byte[] imgArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Create_Location", ReplyAction="http://tempuri.org/IService1/Create_LocationResponse")]
        int Create_Location(WpfApp6.ServiceReference1.Location loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Create_Location", ReplyAction="http://tempuri.org/IService1/Create_LocationResponse")]
        System.Threading.Tasks.Task<int> Create_LocationAsync(WpfApp6.ServiceReference1.Location loc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteC", ReplyAction="http://tempuri.org/IService1/DeleteCResponse")]
        void DeleteC(WpfApp6.ServiceReference1.Comments c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteC", ReplyAction="http://tempuri.org/IService1/DeleteCResponse")]
        System.Threading.Tasks.Task DeleteCAsync(WpfApp6.ServiceReference1.Comments c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteL", ReplyAction="http://tempuri.org/IService1/DeleteLResponse")]
        void DeleteL(WpfApp6.ServiceReference1.Location l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteL", ReplyAction="http://tempuri.org/IService1/DeleteLResponse")]
        System.Threading.Tasks.Task DeleteLAsync(WpfApp6.ServiceReference1.Location l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApp6.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApp6.ServiceReference1.IService1>, WpfApp6.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApp6.ServiceReference1.Person LogIn(string uname, string pass) {
            return base.Channel.LogIn(uname, pass);
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.Person> LogInAsync(string uname, string pass) {
            return base.Channel.LogInAsync(uname, pass);
        }
        
        public int InsertPerson(WpfApp6.ServiceReference1.Person person) {
            return base.Channel.InsertPerson(person);
        }
        
        public System.Threading.Tasks.Task<int> InsertPersonAsync(WpfApp6.ServiceReference1.Person person) {
            return base.Channel.InsertPersonAsync(person);
        }
        
        public WpfApp6.ServiceReference1.STypeList SelectAllTypes() {
            return base.Channel.SelectAllTypes();
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.STypeList> SelectAllTypesAsync() {
            return base.Channel.SelectAllTypesAsync();
        }
        
        public WpfApp6.ServiceReference1.PersonList SelectAllPersons() {
            return base.Channel.SelectAllPersons();
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.PersonList> SelectAllPersonsAsync() {
            return base.Channel.SelectAllPersonsAsync();
        }
        
        public void UpdatePerson(WpfApp6.ServiceReference1.Person p) {
            base.Channel.UpdatePerson(p);
        }
        
        public System.Threading.Tasks.Task UpdatePersonAsync(WpfApp6.ServiceReference1.Person p) {
            return base.Channel.UpdatePersonAsync(p);
        }
        
        public void Delete(WpfApp6.ServiceReference1.Person p) {
            base.Channel.Delete(p);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(WpfApp6.ServiceReference1.Person p) {
            return base.Channel.DeleteAsync(p);
        }
        
        public WpfApp6.ServiceReference1.CommentsList SelectAllC() {
            return base.Channel.SelectAllC();
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.CommentsList> SelectAllCAsync() {
            return base.Channel.SelectAllCAsync();
        }
        
        public WpfApp6.ServiceReference1.LocationList SelectAllL() {
            return base.Channel.SelectAllL();
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.LocationList> SelectAllLAsync() {
            return base.Channel.SelectAllLAsync();
        }
        
        public void comment_creator(WpfApp6.ServiceReference1.Person p, WpfApp6.ServiceReference1.Location loc) {
            base.Channel.comment_creator(p, loc);
        }
        
        public System.Threading.Tasks.Task comment_creatorAsync(WpfApp6.ServiceReference1.Person p, WpfApp6.ServiceReference1.Location loc) {
            return base.Channel.comment_creatorAsync(p, loc);
        }
        
        public WpfApp6.ServiceReference1.CommentsList SelectCbyP(WpfApp6.ServiceReference1.Person p) {
            return base.Channel.SelectCbyP(p);
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.CommentsList> SelectCbyPAsync(WpfApp6.ServiceReference1.Person p) {
            return base.Channel.SelectCbyPAsync(p);
        }
        
        public WpfApp6.ServiceReference1.LocationList Lby_Person(WpfApp6.ServiceReference1.Person p) {
            return base.Channel.Lby_Person(p);
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.LocationList> Lby_PersonAsync(WpfApp6.ServiceReference1.Person p) {
            return base.Channel.Lby_PersonAsync(p);
        }
        
        public WpfApp6.ServiceReference1.LTypeList all_l_types() {
            return base.Channel.all_l_types();
        }
        
        public System.Threading.Tasks.Task<WpfApp6.ServiceReference1.LTypeList> all_l_typesAsync() {
            return base.Channel.all_l_typesAsync();
        }
        
        public byte[] GetImage(string fileName) {
            return base.Channel.GetImage(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName) {
            return base.Channel.GetImageAsync(fileName);
        }
        
        public void SaveImage(byte[] imgArray, string fileName) {
            base.Channel.SaveImage(imgArray, fileName);
        }
        
        public System.Threading.Tasks.Task SaveImageAsync(byte[] imgArray, string fileName) {
            return base.Channel.SaveImageAsync(imgArray, fileName);
        }
        
        public int Create_Location(WpfApp6.ServiceReference1.Location loc) {
            return base.Channel.Create_Location(loc);
        }
        
        public System.Threading.Tasks.Task<int> Create_LocationAsync(WpfApp6.ServiceReference1.Location loc) {
            return base.Channel.Create_LocationAsync(loc);
        }
        
        public void DeleteC(WpfApp6.ServiceReference1.Comments c) {
            base.Channel.DeleteC(c);
        }
        
        public System.Threading.Tasks.Task DeleteCAsync(WpfApp6.ServiceReference1.Comments c) {
            return base.Channel.DeleteCAsync(c);
        }
        
        public void DeleteL(WpfApp6.ServiceReference1.Location l) {
            base.Channel.DeleteL(l);
        }
        
        public System.Threading.Tasks.Task DeleteLAsync(WpfApp6.ServiceReference1.Location l) {
            return base.Channel.DeleteLAsync(l);
        }
    }
}
