//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateApp.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkateApp.ServiceReference1.STypes))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkateApp.ServiceReference1.Comments))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkateApp.ServiceReference1.Location))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkateApp.ServiceReference1.LType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkateApp.ServiceReference1.Person))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STypes", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class STypes : SkateApp.ServiceReference1.BaseEntity {
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comments", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Comments : SkateApp.ServiceReference1.BaseEntity {
        
        private System.DateTime CdateField;
        
        private string CommentField;
        
        private SkateApp.ServiceReference1.Person CreatorField;
        
        private SkateApp.ServiceReference1.Location LocField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Cdate {
            get {
                return this.CdateField;
            }
            set {
                if ((this.CdateField.Equals(value) != true)) {
                    this.CdateField = value;
                    this.RaisePropertyChanged("Cdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkateApp.ServiceReference1.Person Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkateApp.ServiceReference1.Location Loc {
            get {
                return this.LocField;
            }
            set {
                if ((object.ReferenceEquals(this.LocField, value) != true)) {
                    this.LocField = value;
                    this.RaisePropertyChanged("Loc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Location : SkateApp.ServiceReference1.BaseEntity {
        
        private double AltitudeField;
        
        private string DesField;
        
        private double LongitudeField;
        
        private string NameField;
        
        private SkateApp.ServiceReference1.LType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des {
            get {
                return this.DesField;
            }
            set {
                if ((object.ReferenceEquals(this.DesField, value) != true)) {
                    this.DesField = value;
                    this.RaisePropertyChanged("Des");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkateApp.ServiceReference1.LType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LType", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class LType : SkateApp.ServiceReference1.BaseEntity {
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Person : SkateApp.ServiceReference1.BaseEntity {
        
        private bool AdminField;
        
        private string EmailField;
        
        private string PasswordField;
        
        private SkateApp.ServiceReference1.STypes STypeField;
        
        private System.DateTime SYearsField;
        
        private bool TrustedField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkateApp.ServiceReference1.STypes SType {
            get {
                return this.STypeField;
            }
            set {
                if ((object.ReferenceEquals(this.STypeField, value) != true)) {
                    this.STypeField = value;
                    this.RaisePropertyChanged("SType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SYears {
            get {
                return this.SYearsField;
            }
            set {
                if ((this.SYearsField.Equals(value) != true)) {
                    this.SYearsField = value;
                    this.RaisePropertyChanged("SYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Trusted {
            get {
                return this.TrustedField;
            }
            set {
                if ((this.TrustedField.Equals(value) != true)) {
                    this.TrustedField = value;
                    this.RaisePropertyChanged("Trusted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="STypeList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="STypes")]
    public class STypeList : System.Collections.ObjectModel.ObservableCollection<SkateApp.ServiceReference1.STypes> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PersonList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Person")]
    public class PersonList : System.Collections.ObjectModel.ObservableCollection<SkateApp.ServiceReference1.Person> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CommentsList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Comments")]
    public class CommentsList : System.Collections.ObjectModel.ObservableCollection<SkateApp.ServiceReference1.Comments> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LocationList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Location")]
    public class LocationList : System.Collections.ObjectModel.ObservableCollection<SkateApp.ServiceReference1.Location> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LTypeList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="LType")]
    public class LTypeList : System.Collections.ObjectModel.ObservableCollection<SkateApp.ServiceReference1.LType> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/LogIn", ReplyAction="http://tempuri.org/IService1/LogInResponse")]
        System.IAsyncResult BeginLogIn(string uname, string pass, System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.Person EndLogIn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertPerson", ReplyAction="http://tempuri.org/IService1/InsertPersonResponse")]
        System.IAsyncResult BeginInsertPerson(SkateApp.ServiceReference1.Person person, System.AsyncCallback callback, object asyncState);
        
        int EndInsertPerson(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SelectAllTypes", ReplyAction="http://tempuri.org/IService1/SelectAllTypesResponse")]
        System.IAsyncResult BeginSelectAllTypes(System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.STypeList EndSelectAllTypes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SelectAllPersons", ReplyAction="http://tempuri.org/IService1/SelectAllPersonsResponse")]
        System.IAsyncResult BeginSelectAllPersons(System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.PersonList EndSelectAllPersons(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UpdatePerson", ReplyAction="http://tempuri.org/IService1/UpdatePersonResponse")]
        System.IAsyncResult BeginUpdatePerson(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState);
        
        void EndUpdatePerson(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        System.IAsyncResult BeginDelete(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState);
        
        void EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SelectAllC", ReplyAction="http://tempuri.org/IService1/SelectAllCResponse")]
        System.IAsyncResult BeginSelectAllC(System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.CommentsList EndSelectAllC(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SelectAllL", ReplyAction="http://tempuri.org/IService1/SelectAllLResponse")]
        System.IAsyncResult BeginSelectAllL(System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.LocationList EndSelectAllL(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/comment_creator", ReplyAction="http://tempuri.org/IService1/comment_creatorResponse")]
        System.IAsyncResult Begincomment_creator(SkateApp.ServiceReference1.Person p, SkateApp.ServiceReference1.Location loc, System.AsyncCallback callback, object asyncState);
        
        void Endcomment_creator(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SelectCbyP", ReplyAction="http://tempuri.org/IService1/SelectCbyPResponse")]
        System.IAsyncResult BeginSelectCbyP(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.CommentsList EndSelectCbyP(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Lby_Person", ReplyAction="http://tempuri.org/IService1/Lby_PersonResponse")]
        System.IAsyncResult BeginLby_Person(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.LocationList EndLby_Person(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/all_l_types", ReplyAction="http://tempuri.org/IService1/all_l_typesResponse")]
        System.IAsyncResult Beginall_l_types(System.AsyncCallback callback, object asyncState);
        
        SkateApp.ServiceReference1.LTypeList Endall_l_types(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.IAsyncResult BeginGetImage(string fileName, System.AsyncCallback callback, object asyncState);
        
        byte[] EndGetImage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        System.IAsyncResult BeginSaveImage(byte[] imgArray, string fileName, System.AsyncCallback callback, object asyncState);
        
        void EndSaveImage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Create_Location", ReplyAction="http://tempuri.org/IService1/Create_LocationResponse")]
        System.IAsyncResult BeginCreate_Location(SkateApp.ServiceReference1.Location loc, System.AsyncCallback callback, object asyncState);
        
        int EndCreate_Location(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SkateApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.Person Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.Person)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectAllTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.STypeList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.STypeList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectAllPersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllPersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.PersonList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.PersonList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectAllCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.CommentsList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.CommentsList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectAllLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.LocationList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.LocationList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectCbyPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectCbyPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.CommentsList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.CommentsList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Lby_PersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Lby_PersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.LocationList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.LocationList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class all_l_typesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public all_l_typesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkateApp.ServiceReference1.LTypeList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkateApp.ServiceReference1.LTypeList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Create_LocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Create_LocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SkateApp.ServiceReference1.IService1>, SkateApp.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginLogInDelegate;
        
        private EndOperationDelegate onEndLogInDelegate;
        
        private System.Threading.SendOrPostCallback onLogInCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertPersonDelegate;
        
        private EndOperationDelegate onEndInsertPersonDelegate;
        
        private System.Threading.SendOrPostCallback onInsertPersonCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectAllTypesDelegate;
        
        private EndOperationDelegate onEndSelectAllTypesDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllTypesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectAllPersonsDelegate;
        
        private EndOperationDelegate onEndSelectAllPersonsDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllPersonsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePersonDelegate;
        
        private EndOperationDelegate onEndUpdatePersonDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePersonCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectAllCDelegate;
        
        private EndOperationDelegate onEndSelectAllCDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllCCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectAllLDelegate;
        
        private EndOperationDelegate onEndSelectAllLDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllLCompletedDelegate;
        
        private BeginOperationDelegate onBegincomment_creatorDelegate;
        
        private EndOperationDelegate onEndcomment_creatorDelegate;
        
        private System.Threading.SendOrPostCallback oncomment_creatorCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectCbyPDelegate;
        
        private EndOperationDelegate onEndSelectCbyPDelegate;
        
        private System.Threading.SendOrPostCallback onSelectCbyPCompletedDelegate;
        
        private BeginOperationDelegate onBeginLby_PersonDelegate;
        
        private EndOperationDelegate onEndLby_PersonDelegate;
        
        private System.Threading.SendOrPostCallback onLby_PersonCompletedDelegate;
        
        private BeginOperationDelegate onBeginall_l_typesDelegate;
        
        private EndOperationDelegate onEndall_l_typesDelegate;
        
        private System.Threading.SendOrPostCallback onall_l_typesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetImageDelegate;
        
        private EndOperationDelegate onEndGetImageDelegate;
        
        private System.Threading.SendOrPostCallback onGetImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveImageDelegate;
        
        private EndOperationDelegate onEndSaveImageDelegate;
        
        private System.Threading.SendOrPostCallback onSaveImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreate_LocationDelegate;
        
        private EndOperationDelegate onEndCreate_LocationDelegate;
        
        private System.Threading.SendOrPostCallback onCreate_LocationCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LogInCompletedEventArgs> LogInCompleted;
        
        public event System.EventHandler<InsertPersonCompletedEventArgs> InsertPersonCompleted;
        
        public event System.EventHandler<SelectAllTypesCompletedEventArgs> SelectAllTypesCompleted;
        
        public event System.EventHandler<SelectAllPersonsCompletedEventArgs> SelectAllPersonsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdatePersonCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<SelectAllCCompletedEventArgs> SelectAllCCompleted;
        
        public event System.EventHandler<SelectAllLCompletedEventArgs> SelectAllLCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> comment_creatorCompleted;
        
        public event System.EventHandler<SelectCbyPCompletedEventArgs> SelectCbyPCompleted;
        
        public event System.EventHandler<Lby_PersonCompletedEventArgs> Lby_PersonCompleted;
        
        public event System.EventHandler<all_l_typesCompletedEventArgs> all_l_typesCompleted;
        
        public event System.EventHandler<GetImageCompletedEventArgs> GetImageCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveImageCompleted;
        
        public event System.EventHandler<Create_LocationCompletedEventArgs> Create_LocationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginLogIn(string uname, string pass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogIn(uname, pass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.Person SkateApp.ServiceReference1.IService1.EndLogIn(System.IAsyncResult result) {
            return base.Channel.EndLogIn(result);
        }
        
        private System.IAsyncResult OnBeginLogIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uname = ((string)(inValues[0]));
            string pass = ((string)(inValues[1]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginLogIn(uname, pass, callback, asyncState);
        }
        
        private object[] OnEndLogIn(System.IAsyncResult result) {
            SkateApp.ServiceReference1.Person retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndLogIn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogInCompleted(object state) {
            if ((this.LogInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogInCompleted(this, new LogInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogInAsync(string uname, string pass) {
            this.LogInAsync(uname, pass, null);
        }
        
        public void LogInAsync(string uname, string pass, object userState) {
            if ((this.onBeginLogInDelegate == null)) {
                this.onBeginLogInDelegate = new BeginOperationDelegate(this.OnBeginLogIn);
            }
            if ((this.onEndLogInDelegate == null)) {
                this.onEndLogInDelegate = new EndOperationDelegate(this.OnEndLogIn);
            }
            if ((this.onLogInCompletedDelegate == null)) {
                this.onLogInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogInCompleted);
            }
            base.InvokeAsync(this.onBeginLogInDelegate, new object[] {
                        uname,
                        pass}, this.onEndLogInDelegate, this.onLogInCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginInsertPerson(SkateApp.ServiceReference1.Person person, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertPerson(person, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SkateApp.ServiceReference1.IService1.EndInsertPerson(System.IAsyncResult result) {
            return base.Channel.EndInsertPerson(result);
        }
        
        private System.IAsyncResult OnBeginInsertPerson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Person person = ((SkateApp.ServiceReference1.Person)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginInsertPerson(person, callback, asyncState);
        }
        
        private object[] OnEndInsertPerson(System.IAsyncResult result) {
            int retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndInsertPerson(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertPersonCompleted(object state) {
            if ((this.InsertPersonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertPersonCompleted(this, new InsertPersonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertPersonAsync(SkateApp.ServiceReference1.Person person) {
            this.InsertPersonAsync(person, null);
        }
        
        public void InsertPersonAsync(SkateApp.ServiceReference1.Person person, object userState) {
            if ((this.onBeginInsertPersonDelegate == null)) {
                this.onBeginInsertPersonDelegate = new BeginOperationDelegate(this.OnBeginInsertPerson);
            }
            if ((this.onEndInsertPersonDelegate == null)) {
                this.onEndInsertPersonDelegate = new EndOperationDelegate(this.OnEndInsertPerson);
            }
            if ((this.onInsertPersonCompletedDelegate == null)) {
                this.onInsertPersonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertPersonCompleted);
            }
            base.InvokeAsync(this.onBeginInsertPersonDelegate, new object[] {
                        person}, this.onEndInsertPersonDelegate, this.onInsertPersonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginSelectAllTypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAllTypes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.STypeList SkateApp.ServiceReference1.IService1.EndSelectAllTypes(System.IAsyncResult result) {
            return base.Channel.EndSelectAllTypes(result);
        }
        
        private System.IAsyncResult OnBeginSelectAllTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginSelectAllTypes(callback, asyncState);
        }
        
        private object[] OnEndSelectAllTypes(System.IAsyncResult result) {
            SkateApp.ServiceReference1.STypeList retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndSelectAllTypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllTypesCompleted(object state) {
            if ((this.SelectAllTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllTypesCompleted(this, new SelectAllTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllTypesAsync() {
            this.SelectAllTypesAsync(null);
        }
        
        public void SelectAllTypesAsync(object userState) {
            if ((this.onBeginSelectAllTypesDelegate == null)) {
                this.onBeginSelectAllTypesDelegate = new BeginOperationDelegate(this.OnBeginSelectAllTypes);
            }
            if ((this.onEndSelectAllTypesDelegate == null)) {
                this.onEndSelectAllTypesDelegate = new EndOperationDelegate(this.OnEndSelectAllTypes);
            }
            if ((this.onSelectAllTypesCompletedDelegate == null)) {
                this.onSelectAllTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllTypesCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllTypesDelegate, null, this.onEndSelectAllTypesDelegate, this.onSelectAllTypesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginSelectAllPersons(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAllPersons(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.PersonList SkateApp.ServiceReference1.IService1.EndSelectAllPersons(System.IAsyncResult result) {
            return base.Channel.EndSelectAllPersons(result);
        }
        
        private System.IAsyncResult OnBeginSelectAllPersons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginSelectAllPersons(callback, asyncState);
        }
        
        private object[] OnEndSelectAllPersons(System.IAsyncResult result) {
            SkateApp.ServiceReference1.PersonList retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndSelectAllPersons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllPersonsCompleted(object state) {
            if ((this.SelectAllPersonsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllPersonsCompleted(this, new SelectAllPersonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllPersonsAsync() {
            this.SelectAllPersonsAsync(null);
        }
        
        public void SelectAllPersonsAsync(object userState) {
            if ((this.onBeginSelectAllPersonsDelegate == null)) {
                this.onBeginSelectAllPersonsDelegate = new BeginOperationDelegate(this.OnBeginSelectAllPersons);
            }
            if ((this.onEndSelectAllPersonsDelegate == null)) {
                this.onEndSelectAllPersonsDelegate = new EndOperationDelegate(this.OnEndSelectAllPersons);
            }
            if ((this.onSelectAllPersonsCompletedDelegate == null)) {
                this.onSelectAllPersonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllPersonsCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllPersonsDelegate, null, this.onEndSelectAllPersonsDelegate, this.onSelectAllPersonsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginUpdatePerson(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePerson(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SkateApp.ServiceReference1.IService1.EndUpdatePerson(System.IAsyncResult result) {
            base.Channel.EndUpdatePerson(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePerson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Person p = ((SkateApp.ServiceReference1.Person)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginUpdatePerson(p, callback, asyncState);
        }
        
        private object[] OnEndUpdatePerson(System.IAsyncResult result) {
            ((SkateApp.ServiceReference1.IService1)(this)).EndUpdatePerson(result);
            return null;
        }
        
        private void OnUpdatePersonCompleted(object state) {
            if ((this.UpdatePersonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePersonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePersonAsync(SkateApp.ServiceReference1.Person p) {
            this.UpdatePersonAsync(p, null);
        }
        
        public void UpdatePersonAsync(SkateApp.ServiceReference1.Person p, object userState) {
            if ((this.onBeginUpdatePersonDelegate == null)) {
                this.onBeginUpdatePersonDelegate = new BeginOperationDelegate(this.OnBeginUpdatePerson);
            }
            if ((this.onEndUpdatePersonDelegate == null)) {
                this.onEndUpdatePersonDelegate = new EndOperationDelegate(this.OnEndUpdatePerson);
            }
            if ((this.onUpdatePersonCompletedDelegate == null)) {
                this.onUpdatePersonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePersonCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePersonDelegate, new object[] {
                        p}, this.onEndUpdatePersonDelegate, this.onUpdatePersonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginDelete(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SkateApp.ServiceReference1.IService1.EndDelete(System.IAsyncResult result) {
            base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Person p = ((SkateApp.ServiceReference1.Person)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginDelete(p, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            ((SkateApp.ServiceReference1.IService1)(this)).EndDelete(result);
            return null;
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(SkateApp.ServiceReference1.Person p) {
            this.DeleteAsync(p, null);
        }
        
        public void DeleteAsync(SkateApp.ServiceReference1.Person p, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        p}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginSelectAllC(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAllC(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.CommentsList SkateApp.ServiceReference1.IService1.EndSelectAllC(System.IAsyncResult result) {
            return base.Channel.EndSelectAllC(result);
        }
        
        private System.IAsyncResult OnBeginSelectAllC(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginSelectAllC(callback, asyncState);
        }
        
        private object[] OnEndSelectAllC(System.IAsyncResult result) {
            SkateApp.ServiceReference1.CommentsList retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndSelectAllC(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllCCompleted(object state) {
            if ((this.SelectAllCCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllCCompleted(this, new SelectAllCCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllCAsync() {
            this.SelectAllCAsync(null);
        }
        
        public void SelectAllCAsync(object userState) {
            if ((this.onBeginSelectAllCDelegate == null)) {
                this.onBeginSelectAllCDelegate = new BeginOperationDelegate(this.OnBeginSelectAllC);
            }
            if ((this.onEndSelectAllCDelegate == null)) {
                this.onEndSelectAllCDelegate = new EndOperationDelegate(this.OnEndSelectAllC);
            }
            if ((this.onSelectAllCCompletedDelegate == null)) {
                this.onSelectAllCCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllCCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllCDelegate, null, this.onEndSelectAllCDelegate, this.onSelectAllCCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginSelectAllL(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAllL(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.LocationList SkateApp.ServiceReference1.IService1.EndSelectAllL(System.IAsyncResult result) {
            return base.Channel.EndSelectAllL(result);
        }
        
        private System.IAsyncResult OnBeginSelectAllL(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginSelectAllL(callback, asyncState);
        }
        
        private object[] OnEndSelectAllL(System.IAsyncResult result) {
            SkateApp.ServiceReference1.LocationList retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndSelectAllL(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllLCompleted(object state) {
            if ((this.SelectAllLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllLCompleted(this, new SelectAllLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllLAsync() {
            this.SelectAllLAsync(null);
        }
        
        public void SelectAllLAsync(object userState) {
            if ((this.onBeginSelectAllLDelegate == null)) {
                this.onBeginSelectAllLDelegate = new BeginOperationDelegate(this.OnBeginSelectAllL);
            }
            if ((this.onEndSelectAllLDelegate == null)) {
                this.onEndSelectAllLDelegate = new EndOperationDelegate(this.OnEndSelectAllL);
            }
            if ((this.onSelectAllLCompletedDelegate == null)) {
                this.onSelectAllLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllLCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllLDelegate, null, this.onEndSelectAllLDelegate, this.onSelectAllLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.Begincomment_creator(SkateApp.ServiceReference1.Person p, SkateApp.ServiceReference1.Location loc, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begincomment_creator(p, loc, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SkateApp.ServiceReference1.IService1.Endcomment_creator(System.IAsyncResult result) {
            base.Channel.Endcomment_creator(result);
        }
        
        private System.IAsyncResult OnBegincomment_creator(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Person p = ((SkateApp.ServiceReference1.Person)(inValues[0]));
            SkateApp.ServiceReference1.Location loc = ((SkateApp.ServiceReference1.Location)(inValues[1]));
            return ((SkateApp.ServiceReference1.IService1)(this)).Begincomment_creator(p, loc, callback, asyncState);
        }
        
        private object[] OnEndcomment_creator(System.IAsyncResult result) {
            ((SkateApp.ServiceReference1.IService1)(this)).Endcomment_creator(result);
            return null;
        }
        
        private void Oncomment_creatorCompleted(object state) {
            if ((this.comment_creatorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.comment_creatorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void comment_creatorAsync(SkateApp.ServiceReference1.Person p, SkateApp.ServiceReference1.Location loc) {
            this.comment_creatorAsync(p, loc, null);
        }
        
        public void comment_creatorAsync(SkateApp.ServiceReference1.Person p, SkateApp.ServiceReference1.Location loc, object userState) {
            if ((this.onBegincomment_creatorDelegate == null)) {
                this.onBegincomment_creatorDelegate = new BeginOperationDelegate(this.OnBegincomment_creator);
            }
            if ((this.onEndcomment_creatorDelegate == null)) {
                this.onEndcomment_creatorDelegate = new EndOperationDelegate(this.OnEndcomment_creator);
            }
            if ((this.oncomment_creatorCompletedDelegate == null)) {
                this.oncomment_creatorCompletedDelegate = new System.Threading.SendOrPostCallback(this.Oncomment_creatorCompleted);
            }
            base.InvokeAsync(this.onBegincomment_creatorDelegate, new object[] {
                        p,
                        loc}, this.onEndcomment_creatorDelegate, this.oncomment_creatorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginSelectCbyP(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectCbyP(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.CommentsList SkateApp.ServiceReference1.IService1.EndSelectCbyP(System.IAsyncResult result) {
            return base.Channel.EndSelectCbyP(result);
        }
        
        private System.IAsyncResult OnBeginSelectCbyP(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Person p = ((SkateApp.ServiceReference1.Person)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginSelectCbyP(p, callback, asyncState);
        }
        
        private object[] OnEndSelectCbyP(System.IAsyncResult result) {
            SkateApp.ServiceReference1.CommentsList retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndSelectCbyP(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectCbyPCompleted(object state) {
            if ((this.SelectCbyPCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectCbyPCompleted(this, new SelectCbyPCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectCbyPAsync(SkateApp.ServiceReference1.Person p) {
            this.SelectCbyPAsync(p, null);
        }
        
        public void SelectCbyPAsync(SkateApp.ServiceReference1.Person p, object userState) {
            if ((this.onBeginSelectCbyPDelegate == null)) {
                this.onBeginSelectCbyPDelegate = new BeginOperationDelegate(this.OnBeginSelectCbyP);
            }
            if ((this.onEndSelectCbyPDelegate == null)) {
                this.onEndSelectCbyPDelegate = new EndOperationDelegate(this.OnEndSelectCbyP);
            }
            if ((this.onSelectCbyPCompletedDelegate == null)) {
                this.onSelectCbyPCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectCbyPCompleted);
            }
            base.InvokeAsync(this.onBeginSelectCbyPDelegate, new object[] {
                        p}, this.onEndSelectCbyPDelegate, this.onSelectCbyPCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginLby_Person(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLby_Person(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.LocationList SkateApp.ServiceReference1.IService1.EndLby_Person(System.IAsyncResult result) {
            return base.Channel.EndLby_Person(result);
        }
        
        private System.IAsyncResult OnBeginLby_Person(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Person p = ((SkateApp.ServiceReference1.Person)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginLby_Person(p, callback, asyncState);
        }
        
        private object[] OnEndLby_Person(System.IAsyncResult result) {
            SkateApp.ServiceReference1.LocationList retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndLby_Person(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLby_PersonCompleted(object state) {
            if ((this.Lby_PersonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Lby_PersonCompleted(this, new Lby_PersonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Lby_PersonAsync(SkateApp.ServiceReference1.Person p) {
            this.Lby_PersonAsync(p, null);
        }
        
        public void Lby_PersonAsync(SkateApp.ServiceReference1.Person p, object userState) {
            if ((this.onBeginLby_PersonDelegate == null)) {
                this.onBeginLby_PersonDelegate = new BeginOperationDelegate(this.OnBeginLby_Person);
            }
            if ((this.onEndLby_PersonDelegate == null)) {
                this.onEndLby_PersonDelegate = new EndOperationDelegate(this.OnEndLby_Person);
            }
            if ((this.onLby_PersonCompletedDelegate == null)) {
                this.onLby_PersonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLby_PersonCompleted);
            }
            base.InvokeAsync(this.onBeginLby_PersonDelegate, new object[] {
                        p}, this.onEndLby_PersonDelegate, this.onLby_PersonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.Beginall_l_types(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginall_l_types(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateApp.ServiceReference1.LTypeList SkateApp.ServiceReference1.IService1.Endall_l_types(System.IAsyncResult result) {
            return base.Channel.Endall_l_types(result);
        }
        
        private System.IAsyncResult OnBeginall_l_types(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SkateApp.ServiceReference1.IService1)(this)).Beginall_l_types(callback, asyncState);
        }
        
        private object[] OnEndall_l_types(System.IAsyncResult result) {
            SkateApp.ServiceReference1.LTypeList retVal = ((SkateApp.ServiceReference1.IService1)(this)).Endall_l_types(result);
            return new object[] {
                    retVal};
        }
        
        private void Onall_l_typesCompleted(object state) {
            if ((this.all_l_typesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.all_l_typesCompleted(this, new all_l_typesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void all_l_typesAsync() {
            this.all_l_typesAsync(null);
        }
        
        public void all_l_typesAsync(object userState) {
            if ((this.onBeginall_l_typesDelegate == null)) {
                this.onBeginall_l_typesDelegate = new BeginOperationDelegate(this.OnBeginall_l_types);
            }
            if ((this.onEndall_l_typesDelegate == null)) {
                this.onEndall_l_typesDelegate = new EndOperationDelegate(this.OnEndall_l_types);
            }
            if ((this.onall_l_typesCompletedDelegate == null)) {
                this.onall_l_typesCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onall_l_typesCompleted);
            }
            base.InvokeAsync(this.onBeginall_l_typesDelegate, null, this.onEndall_l_typesDelegate, this.onall_l_typesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginGetImage(string fileName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetImage(fileName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] SkateApp.ServiceReference1.IService1.EndGetImage(System.IAsyncResult result) {
            return base.Channel.EndGetImage(result);
        }
        
        private System.IAsyncResult OnBeginGetImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileName = ((string)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginGetImage(fileName, callback, asyncState);
        }
        
        private object[] OnEndGetImage(System.IAsyncResult result) {
            byte[] retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndGetImage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetImageCompleted(object state) {
            if ((this.GetImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetImageCompleted(this, new GetImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetImageAsync(string fileName) {
            this.GetImageAsync(fileName, null);
        }
        
        public void GetImageAsync(string fileName, object userState) {
            if ((this.onBeginGetImageDelegate == null)) {
                this.onBeginGetImageDelegate = new BeginOperationDelegate(this.OnBeginGetImage);
            }
            if ((this.onEndGetImageDelegate == null)) {
                this.onEndGetImageDelegate = new EndOperationDelegate(this.OnEndGetImage);
            }
            if ((this.onGetImageCompletedDelegate == null)) {
                this.onGetImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetImageCompleted);
            }
            base.InvokeAsync(this.onBeginGetImageDelegate, new object[] {
                        fileName}, this.onEndGetImageDelegate, this.onGetImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginSaveImage(byte[] imgArray, string fileName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveImage(imgArray, fileName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SkateApp.ServiceReference1.IService1.EndSaveImage(System.IAsyncResult result) {
            base.Channel.EndSaveImage(result);
        }
        
        private System.IAsyncResult OnBeginSaveImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte[] imgArray = ((byte[])(inValues[0]));
            string fileName = ((string)(inValues[1]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginSaveImage(imgArray, fileName, callback, asyncState);
        }
        
        private object[] OnEndSaveImage(System.IAsyncResult result) {
            ((SkateApp.ServiceReference1.IService1)(this)).EndSaveImage(result);
            return null;
        }
        
        private void OnSaveImageCompleted(object state) {
            if ((this.SaveImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveImageAsync(byte[] imgArray, string fileName) {
            this.SaveImageAsync(imgArray, fileName, null);
        }
        
        public void SaveImageAsync(byte[] imgArray, string fileName, object userState) {
            if ((this.onBeginSaveImageDelegate == null)) {
                this.onBeginSaveImageDelegate = new BeginOperationDelegate(this.OnBeginSaveImage);
            }
            if ((this.onEndSaveImageDelegate == null)) {
                this.onEndSaveImageDelegate = new EndOperationDelegate(this.OnEndSaveImage);
            }
            if ((this.onSaveImageCompletedDelegate == null)) {
                this.onSaveImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveImageCompleted);
            }
            base.InvokeAsync(this.onBeginSaveImageDelegate, new object[] {
                        imgArray,
                        fileName}, this.onEndSaveImageDelegate, this.onSaveImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SkateApp.ServiceReference1.IService1.BeginCreate_Location(SkateApp.ServiceReference1.Location loc, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreate_Location(loc, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SkateApp.ServiceReference1.IService1.EndCreate_Location(System.IAsyncResult result) {
            return base.Channel.EndCreate_Location(result);
        }
        
        private System.IAsyncResult OnBeginCreate_Location(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkateApp.ServiceReference1.Location loc = ((SkateApp.ServiceReference1.Location)(inValues[0]));
            return ((SkateApp.ServiceReference1.IService1)(this)).BeginCreate_Location(loc, callback, asyncState);
        }
        
        private object[] OnEndCreate_Location(System.IAsyncResult result) {
            int retVal = ((SkateApp.ServiceReference1.IService1)(this)).EndCreate_Location(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreate_LocationCompleted(object state) {
            if ((this.Create_LocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Create_LocationCompleted(this, new Create_LocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Create_LocationAsync(SkateApp.ServiceReference1.Location loc) {
            this.Create_LocationAsync(loc, null);
        }
        
        public void Create_LocationAsync(SkateApp.ServiceReference1.Location loc, object userState) {
            if ((this.onBeginCreate_LocationDelegate == null)) {
                this.onBeginCreate_LocationDelegate = new BeginOperationDelegate(this.OnBeginCreate_Location);
            }
            if ((this.onEndCreate_LocationDelegate == null)) {
                this.onEndCreate_LocationDelegate = new EndOperationDelegate(this.OnEndCreate_Location);
            }
            if ((this.onCreate_LocationCompletedDelegate == null)) {
                this.onCreate_LocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreate_LocationCompleted);
            }
            base.InvokeAsync(this.onBeginCreate_LocationDelegate, new object[] {
                        loc}, this.onEndCreate_LocationDelegate, this.onCreate_LocationCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SkateApp.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://10.116.8.30:8733/Design_Time_Addresses/ServiceLibary/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private class Service1ClientChannel : ChannelBase<SkateApp.ServiceReference1.IService1>, SkateApp.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<SkateApp.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogIn(string uname, string pass, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = uname;
                _args[1] = pass;
                System.IAsyncResult _result = base.BeginInvoke("LogIn", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.Person EndLogIn(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.Person _result = ((SkateApp.ServiceReference1.Person)(base.EndInvoke("LogIn", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertPerson(SkateApp.ServiceReference1.Person person, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = person;
                System.IAsyncResult _result = base.BeginInvoke("InsertPerson", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertPerson(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertPerson", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectAllTypes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SelectAllTypes", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.STypeList EndSelectAllTypes(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.STypeList _result = ((SkateApp.ServiceReference1.STypeList)(base.EndInvoke("SelectAllTypes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectAllPersons(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SelectAllPersons", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.PersonList EndSelectAllPersons(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.PersonList _result = ((SkateApp.ServiceReference1.PersonList)(base.EndInvoke("SelectAllPersons", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdatePerson(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("UpdatePerson", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdatePerson(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdatePerson", _args, result);
            }
            
            public System.IAsyncResult BeginDelete(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Delete", _args, result);
            }
            
            public System.IAsyncResult BeginSelectAllC(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SelectAllC", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.CommentsList EndSelectAllC(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.CommentsList _result = ((SkateApp.ServiceReference1.CommentsList)(base.EndInvoke("SelectAllC", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectAllL(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SelectAllL", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.LocationList EndSelectAllL(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.LocationList _result = ((SkateApp.ServiceReference1.LocationList)(base.EndInvoke("SelectAllL", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Begincomment_creator(SkateApp.ServiceReference1.Person p, SkateApp.ServiceReference1.Location loc, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = p;
                _args[1] = loc;
                System.IAsyncResult _result = base.BeginInvoke("comment_creator", _args, callback, asyncState);
                return _result;
            }
            
            public void Endcomment_creator(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("comment_creator", _args, result);
            }
            
            public System.IAsyncResult BeginSelectCbyP(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("SelectCbyP", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.CommentsList EndSelectCbyP(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.CommentsList _result = ((SkateApp.ServiceReference1.CommentsList)(base.EndInvoke("SelectCbyP", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLby_Person(SkateApp.ServiceReference1.Person p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("Lby_Person", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.LocationList EndLby_Person(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.LocationList _result = ((SkateApp.ServiceReference1.LocationList)(base.EndInvoke("Lby_Person", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginall_l_types(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("all_l_types", _args, callback, asyncState);
                return _result;
            }
            
            public SkateApp.ServiceReference1.LTypeList Endall_l_types(System.IAsyncResult result) {
                object[] _args = new object[0];
                SkateApp.ServiceReference1.LTypeList _result = ((SkateApp.ServiceReference1.LTypeList)(base.EndInvoke("all_l_types", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetImage(string fileName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = fileName;
                System.IAsyncResult _result = base.BeginInvoke("GetImage", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndGetImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("GetImage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveImage(byte[] imgArray, string fileName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = imgArray;
                _args[1] = fileName;
                System.IAsyncResult _result = base.BeginInvoke("SaveImage", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveImage", _args, result);
            }
            
            public System.IAsyncResult BeginCreate_Location(SkateApp.ServiceReference1.Location loc, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = loc;
                System.IAsyncResult _result = base.BeginInvoke("Create_Location", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreate_Location(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Create_Location", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
